
#datasource
spring:
  application:
    name: javari-game-service
  datasource:
    url: jdbc:mysql://localhost:3306/javaridb
    username: ${JAVARI_DB_USER:root}
    password: ${JAVARI_DB_PASSWORD:javari}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        ddl-auto: update
    show-sql: true
    generate-ddl: true
  sql:
    init.mode: always
  main:
    allow-bean-definition-overriding: true

#eureka config
eureka:
  instance:
    prefer-ip-address: false
    hostname: javari-discovery-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8082

feign:
  client:
    config:
      default:
        loggerLevel: full

files:
  uploadDir: /Users/dario/mnt/storage/javari_files/