server:
  port: 0
api:
  core:
    url: "http://game"
javari:
  client:
    front: "http://javari-front"
spring:
  application:
    name: javari-connector-service

#eureka config
eureka:
  instance:
    prefer-ip-address: false
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org:
      springframework:
        security: debug
