server:
  port: 0
api:
  core:
    url: "http://localhost:8081"
javari:
  client:
    front: "http://localhost:8081"
spring:
  application:
    name: javari-connector-service

#eureka config
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
