server:
  port: 8080
spring:
  application:
    name: javari-gateway
  cloud:
    gateway:
      routes:
        - id: javari-auth-service
          uri: lb://javari-auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: javari-game-service
          uri: lb://javari-game-service
          predicates:
            - Path=/api/v1/game/**
        - id: javari-connector-service
          uri: lb://javari-connector-service
          predicates:
            - Path=/api/v1/connector/loader/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://darioteodoro.dev.br"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
          route:
            RouteDefinitionLocator: debug
